alias ls="ls -A --color=auto"
alias ll="ls -Ahl --color=auto --time-style=long-iso"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias grep="grep --color=auto"
alias mv="mv -i"
alias rm="rm -i"
alias which="alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde"
alias saltlo="salt-call --local"
